lib/dht.go
lib/log.go
lib/vars.go
main.go
p2p-cp/cp.go
p2p.go

Issues with forwarding are going to be fixed with this Pull Reuqest

Fix forwarding

---

lib/dht.go
lib/vars.go
p2p-cp/cp.go

Closes #31: DHT server optimizations has been applied
Fixes #20: Control peer operation stabilized
Fixes #19: Routing mechanics has been changed

Multiple optimizations, bug fixes and improvements

---

p2p.go

Added new map for MAC->ID which allows faster lookup for a target peer.

---

instance.go
lib/net.go
lib/vars.go
main.go
p2p-cp/proxy.go
p2p.go

*  Added new p2p message type which will be used to notify peers about dead tunnel.
*  Added -port argument that allows users to use specific ports for their p2p communication

Remove proxy command and port specification

---

instance.go
lib/p2p.go
p2p-cp/cp.go

Now DHCP request will finish after 10 retries
DHCP data on DHT server is now persistent

Show is not blocking anymore.

---

instance.go
lib/crypto.go
lib/peer.go

Fixes #183 : Safe show command
Fixes #184

Clean logs

---

lib/tuntap_windows.go

Implemented a workaround by assigning fake ip addresses to TAP Interfaces. 

---

CHANGELOG
instance.go
lib/p2p.go

Changed lock order. Changed RLock to Lock

---

Makefile
lib/p2p.go

* Introduced build of Windows and Macos version from Makefile
* Fixed intervals to reduce CPU load. Closes #242

New crossplatform build and reduced CPU load

---

Jenkinsfile

Fixed p2p binay call
Chaned version to full

[Jenkinsfile] Added ‘version’ field for p2p artifacts on kurjun #253

---

lib/tuntap_windows.go

Related to : https://github.com/subutai-io/p2p/issues/240

Bugfix : Non English version of Windows.

---

.gitignore
lib/tuntap_posix.go

user.Current() replaced with Getuid() call to avoid errors on MacOS.

---

lib/log.go

Signed-off-by: Dmitry Shihovtsev <soffokulus@gmail.com>

Fixed call syslog on empty flag

---

lib/dht.go
lib/p2p.go

Signed-off-by: Dmitry Shihovtsev <soffokulus@gmail.com>

Fixed deleting multiple connection. #360

---

lib/dht.go
lib/p2p.go

Removed unnecessary goroutines

Fixed missing State DHT command handler.

---

instance.go
lib/p2p.go
lib/peer.go
lib/vars.go

Added several state handlers when peers are connected

Fixed handshaking

---

Jenkinsfile

Fixed Jenkins file upload

---

lib/crypto.go
lib/packet_handler.go
lib/proxy.go

Fixed proxy disconnect by timeout when communication actually works.
Fixed crash of crypto subsystem. Closes #613

Fixing proxies

---

lib/p2p.go
lib/tuntap_windows.go

Fixed interface configuration

---

lib/p2p.go
lib/peer.go

Now both peers will try to reach "Waiting To Connect" state,
before attempting any connections

Several fixes in peer management

---

lib/tuntap_linux.go

ifconfig eth down
set mac
then
ifconfig eth up

fix centos set mac failed

---

dht.go
lib/dht.go
lib/p2p.go
lib/packet.go
start.go

Fixed problem with hanging channel in DHT client,
after closing any of previous instances, main reading
channel was blocked.

Fixed environment creation

---

lib/dht.go

Removed packet split for large packets

Minor fix for DHT packet

---

CODEOWNERS
lib/packet_handler.go
lib/peer.go

Reduced overall p2p traffic
Modified endpoint ping

Connectivity fixes

---

instance.go
instance_test.go

Modified the encoding and decoding of instances, added instance_test.go, but issue is not solved yet.

#799. Modified the encoding and decoding of instances

---

instance_test.go

Added tests to TestEncodeInstances. 
Will work more on other functions such as TestDecodeInstances, TestSaveInstances, TestLoadInstances after my class.

Adding more tests

---

instance_test.go

Completed TestEncodeInstances and TestDecodeInstances.

Completed TestEncodeInstances and TestDecodeInstances

---

dht_router.go

Fixed bug in handleData in dht_router.go

---

daemon.go
lib/dht.go

Added DHT packets splitting. For review

---

service_windows.go

* Added one more fix for issue #774 
Requiring more testing and review.

#774 for second testing and review

---

.travis.yml
lib/dht.go
lib/utils.go

Moved auxiliary function to utils.go
Moved auxiliary function min(a, b) from lib/dht.go to utils.go

Moved auxiliary function to utils.go

---

instance.go
instance_test.go

Fixed instance_test.go for new encoding style and added small fix in 151 line of instance.go

Fixed instance_test.go for new encoding style and added small fix in 151 line of instance.go

---

instance.go
instance_test.go

Added fix to not to write on the old p2p.save file
Added fix to not to write on the old p2p.save file but recreate a new instead and added tests for this fix.

Added fix to not to write on the old p2p.save file

---

dht_connection.go

Added additional log trace in dht_connection.go
Added additional log trace in dht_connection.go

Added additional log trace in dht_connection.go

---

lib/dht_test.go

Added new tests in dht_test.go
Added new tests in dht_test.go that check proto.Marshal and proto.Unmarshal processes.

Added new tests in dht_test.go

---

dht_router.go

Added more verbosity in routeData
Added more verbosity in routeData (dht_router.go) to see what corrupted data from DHT looks like.

Added more verbosity in routeData

---

Makefile
configure
dht_router.go

Added more verbosity in handleData
Added more verbosity in handleData (dht_router.go) to see how much data is being parsed to routeData (dht_router.go).

Added more verbosity in handleData

---

dht_router.go
dht_test.go
lib/vars.go

Using variable instead of hardcoded value
Variable is set to 4K

Modified DHT buffer size

---

lib/platform_windows.go

Added Administrator permission checking for Windows platform
Added Administrator permission checking for Windows platform in lib/platform_windows.go, function CheckPermissions.

Added Administrator permission checking for Windows platform

---

lib/packet_handler.go

Added peer disconnect when same MAC or endpoints are active
on another peer

Disconnect duplicate peers

---

lib/dht.go
lib/dht_test.go

Completely covered dht.go with tests
Completely covered dht.go with tests (dht_test.go) and added several small checks in dht.go

Completely covered dht.go with tests

---

daemon.go
lib/log.go
main.go
set.go

Added enhancement #930
Added enhancement #930.

Added enhancement #930
